@extends('layouts.app') 
@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Politique de confidentialité</div>
                <div class="panel-body">
                    
                    <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 11pt; background-color: #ffffff;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Derni&egrave;re mise &agrave; jour : 19 juin 2017</span></p>
                    <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 11pt; background-color: #ffffff;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Merci d&rsquo;utiliser My Ice Tool !</span></p>
                    <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 11pt; background-color: #ffffff;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">La pr&eacute;sente Charte de protection des donn&eacute;es &agrave; caract&egrave;re personnel d&eacute;crit la fa&ccedil;on dont nous collectons, utilisons, traitons et divulguons les informations vous concernant sur l&rsquo;ensemble de notre Plateforme.</span></p>
                    
                    <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 11pt; background-color: #ffffff;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Lorsque cette charte fait mention des termes &laquo; My Ice Tool &raquo;, &laquo; nous &raquo;, &laquo; notre &raquo; ou &laquo; nos &raquo;, ils font r&eacute;f&eacute;rence &agrave; la soci&eacute;t&eacute; My Ice Tool, laquelle est responsable des informations vous concernant conform&eacute;ment &agrave; la pr&eacute;sente Charte de protection des donn&eacute;es &agrave; caract&egrave;re personnel </span></p>
                    <p>&nbsp;</p>
                    <h4 style="line-height: 1.32; margin-top: 19pt; margin-bottom: 11pt; background-color: #ffffff;"><strong><span style="font-size: 13.5pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">1. INFORMATIONS COLLECT&Eacute;ES</span></strong></h4>
                    <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 11pt; background-color: #ffffff;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Nous collectons trois cat&eacute;gories g&eacute;n&eacute;rales d&rsquo;informations.</span></p>
                    <h5 style="line-height: 1.32; margin-top: 19pt; margin-bottom: 11pt; background-color: #ffffff;"><strong><span style="font-size: 12pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">1.1 Informations que vous nous communiquez.</span></strong></h5>
                    <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 11pt; background-color: #ffffff;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Nous collectons les informations que vous nous communiquez lors de votre utilisation de la Plateforme My Ice Tool.</span></p>
                    <ul style="margin-top: 0pt; margin-bottom: 0pt;">
                        <li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><strong><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Informations de compte.</span></strong>
                            <span
                                style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">
                            Lors de la cr&eacute;ation de votre compte My Ice Tool, nous vous demandons de nous communiquer
                                certaines informations comme votre nom, adresse e-mail.</span>
                        </li>
                        <li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><strong><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Informations de profil.</span></strong>
                            <span
                                style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">
                            Afin d&rsquo;utiliser certaines fonctionnalit&eacute;s sur la Plateforme My Ice Tool, il se peut
                                que nous vous demandions &eacute;galement de renseigner un profil, pouvant comprendre votre
                                num&eacute;ro de t&eacute;l&eacute;phone. Certaines parties de votre profil (comme votre
                                photo de profil, pr&eacute;nom) font partie de votre page de profil public, et pourront &ecirc;tre
                                consult&eacute;es par d&rsquo;autres personnes.</span>
                        </li>
                        <li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><strong><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Autres informations d&rsquo;authentification.</span></strong>
                            <span
                                style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">
                            Pour contribuer &agrave; la cr&eacute;ation et au maintien d&rsquo;un environnement de confiance,
                                nous pouvons collecter des informations servant &agrave; vous identifier (comme une photo
                                de votre Carte Nationale d&rsquo;Identit&eacute;) ou autres informations d&rsquo;authentification.
                                Pour en savoir plus, lisez l&rsquo;article de notre Centre d&rsquo;aide concernant </span>
                                <a
                                    style="text-decoration: none;" href="https://www.airbnb.fr/help/article/1237/how-does-providing-identification-on-airbnb-work"><span style="font-size: 10.5pt; font-family: Arial; color: #008489; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: underline; -webkit-text-decoration-skip: none; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">la V&eacute;rification</span></a>
                                    <span
                                        style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">.</span>
                        </li>
                        <li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><strong><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Informations de paiement.</span></strong>
                            <span
                                style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">
                            Nous collectons les informations financi&egrave;res vous concernant (comme les donn&eacute;es
                                relatives &agrave; votre compte bancaire ou &agrave; votre carte de cr&eacute;dit) lorsque
                                vous utilisez les Services de paiement dans le cadre du traitement des paiements.</span>
                        </li>
                        <li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><strong><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Communications avec My Ice Tool et les autres membres.</span></strong>
                            <span
                                style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">
                            Lorsque vous communiquez avec My Ice Tool ou que vous utilisez la Plateforme pour communiquer
                                avec d&rsquo;autres Membres, nous collectons des informations concernant vos communications
                                et toute information que vous d&eacute;cidez de transmettre.</span>
                        </li>
                        <li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><strong><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Autres informations.</span></strong>
                            <span
                                style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">
                            Autrement, vous pouvez choisir de nous communiquer des informations lorsque vous remplissez un
                                formulaire, menez une recherche, mettez &agrave; jour ou ajoutez des informations &agrave;
                                votre Compte My Ice Tool, r&eacute;pondez &agrave; des enqu&ecirc;tes, publiez sur les forums
                                de discussion, participez &agrave; des op&eacute;rations de promotion ou utilisez d&rsquo;autres
                                fonctionnalit&eacute;s de la Plateforme My Ice Tool.</span>
                        </li>
                    </ul>
                    <h5 style="line-height: 1.32; margin-top: 19pt; margin-bottom: 11pt; background-color: #ffffff;"><strong><span style="font-size: 12pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">1.2 Informations que nous collectons automatiquement lors de votre utilisation de la Plateforme My Ice Tool.</span></strong></h5>
                    <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 11pt; background-color: #ffffff;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Lorsque vous utilisez la Plateforme My Ice Tool, nous collectons des informations concernant les services que vous utilisez et la fa&ccedil;on dont vous les utilisez.</span></p>
                    <ul style="margin-top: 0pt; margin-bottom: 0pt;">
                        <li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><strong><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Informations de localisation.</span></strong>
                            <span
                                style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">
                            Lors de votre utilisation de certaines fonctionnalit&eacute;s de la Plateforme My Ice Tool, nous
                                pouvons collecter diff&eacute;rents types d&rsquo;informations concernant votre emplacement
                                g&eacute;n&eacute;ral (par ex. adresse IP, code postal) ou des renseignements plus sp&eacute;cifiques
                                de localisation (par ex. la localisation pr&eacute;cise depuis le GPS de votre appareil mobile).
                                La majorit&eacute; des appareils mobiles vous permet de contr&ocirc;ler ou d&eacute;sactiver
                                l&rsquo;utilisation des services de localisation dans les applications &agrave; partir du
                                menu des param&egrave;tres de l&rsquo;appareil.</span>
                        </li>
                        <li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><strong><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Donn&eacute;es de connexion.</span></strong>
                            <span
                                style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">
                            Nous collectons automatiquement les informations de connexion lors de votre utilisation de la
                                Plateforme My Ice Tool, m&ecirc;me si vous n&rsquo;avez pas cr&eacute;&eacute; de compte
                                My Ice Tool ou n&rsquo;&ecirc;tes pas connect&eacute;. Ces informations comprennent, entre
                                autres : des informations sur la fa&ccedil;on dont vous avez utilis&eacute; la Plateforme
                                My Ice Tool (y compris les liens vers les applications de tiers), l'adresse IP, les heures
                                d&rsquo;acc&egrave;s, les donn&eacute;es sur le mat&eacute;riel et le logiciel informatiques,
                                les donn&eacute;es sur l&rsquo;appareil, les donn&eacute;es sur l&rsquo;&eacute;v&eacute;nement
                                de l&rsquo;appareil (par ex. plantages, type de navigateur), et la page que vous avez visualis&eacute;e
                                ou affich&eacute;e avant ou apr&egrave;s avoir utilis&eacute; notre Plateforme.</span>
                        </li>
                        <li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><strong><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Cookies et technologies analogues.</span></strong>
                            <span
                                style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">
                            Nous utilisons des cookies ou d&rsquo;autres technologies analogues, comme les balises web, pixels
                                et identifiants d&rsquo;&eacute;quipement mobile. Nous pouvons &eacute;galement autoriser
                                nos partenaires commerciaux &agrave; utiliser ces technologies de tra&ccedil;age sur la Plateforme
                                My Ice Tool, ou souscrire les services de tiers pour proc&eacute;der au tra&ccedil;age de
                                votre comportement pour notre compte. M&ecirc;me si vous avez la possibilit&eacute; de d&eacute;sactiver
                                les cookies &agrave; partir des param&egrave;tres de votre navigateur, nous ne modifions
                                pas nos pratiques en r&eacute;ponse &agrave; un signal &laquo; Ne pas suivre &raquo; dans
                                l&rsquo;ent&ecirc;te HTTP de votre navigateur ou application mobile. Pour obtenir plus d&rsquo;informations
                                sur l&rsquo;utilisation que nous faisons de ces technologies, veuillez consulter notre </span>
                                <a
                                    style="text-decoration: none;" href="https://www.airbnb.fr/terms/cookie_policy"><span style="font-size: 10.5pt; font-family: Arial; color: #008489; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: underline; -webkit-text-decoration-skip: none; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">Politique relative aux cookies</span></a>
                                    <span
                                        style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">.</span>
                        </li>
                    </ul>
                    <h5 style="line-height: 1.32; margin-top: 19pt; margin-bottom: 11pt; background-color: #ffffff;"><strong><span style="font-size: 12pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">1.3 Informations que nous collectons aupr&egrave;s de tiers.</span></strong></h5>
                    <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 11pt; background-color: #ffffff;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Nous pouvons collecter des informations fournies par des tiers vous concernant lors de leur utilisation de la Plateforme My Ice Tool, ou obtenir des informations aupr&egrave;s d&rsquo;autres sources et les combiner avec celles que nous collectons sur notre Plateforme.</span></p>
                    <ul style="margin-top: 0pt; margin-bottom: 0pt;">
                        <li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><strong><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Services de tiers.</span></strong>
                            <span
                                style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">
                            Si vous liez, associez ou connectez votre Compte My Ice Tool &agrave; un service fourni par un
                                tiers (par ex. Facebook, WeChat), le service fourni par le tiers peut nous envoyer des informations,
                                comme par exemple les informations relatives &agrave; votre inscription et &agrave; votre
                                profil aupr&egrave;s du service en question. Ces informations varient et sont contr&ocirc;l&eacute;es
                                par le service du tiers ou d&eacute;pendent des autorisations que vous avez transmises &agrave;
                                ce service via les param&egrave;tres de confidentialit&eacute; y aff&eacute;rent.</span>
                        </li>
                        <li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><strong><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Vos commentaires.</span></strong>
                            <span
                                style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">
                            Si une personne a &eacute;crit un commentaire sur vous, il sera publi&eacute; sur la page de
                                votre profil public My Ice Tool. Pour en savoir plus sur la fa&ccedil;on dont cela fonctionne,
                                veuillez consulter l&rsquo;article du Centre d&rsquo;aide concernant </span><a style="text-decoration: none;"
                                    href="https://www.airbnb.fr/help/article/173/what-are-references-on-airbnb"><span style="font-size: 10.5pt; font-family: Arial; color: #008489; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: underline; -webkit-text-decoration-skip: none; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">Commentaires</span></a>
                                <span
                                    style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">.</span>
                        </li>
                        <li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><strong><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Informations sur les ant&eacute;c&eacute;dents.</span></strong>
                            <span
                                style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">
                            Pour les Membres situ&eacute;s aux &Eacute;tats-Unis, dans la mesure permise par les lois en
                                vigueur, My Ice Tool peut obtenir des rapports aupr&egrave;s de registres publics concernant
                                les condamnations p&eacute;nales ou l&rsquo;inscription au registre des d&eacute;linquants
                                sexuels. Pour les Membres situ&eacute;s en dehors des &Eacute;tats-Unis, dans la mesure permise
                                par les lois en vigueur, My Ice Tool peut obtenir l&rsquo;&eacute;quivalent local de la v&eacute;rification
                                des ant&eacute;c&eacute;dents ou d&rsquo;inscription au registre des d&eacute;linquants sexuels.
                                Nous pouvons utiliser vos informations, notamment votre nom complet et date de naissance,
                                afin d'obtenir ces rapports.</span>
                        </li>
                        <li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><strong><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Autres sources.</span></strong>
                            <span
                                style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">
                            Dans la mesure permise par la loi en vigueur, nous pouvons recevoir des informations compl&eacute;mentaires
                                vous concernant, comme des donn&eacute;es d&eacute;mographiques ou des informations relatives
                                &agrave; la d&eacute;tection des fraudes, de la part de prestataires de services tiers et/ou
                                partenaires, et les combiner avec les informations dont nous disposons sur vous. Par exemple,
                                nous pouvons recevoir les r&eacute;sultats de la v&eacute;rification des ant&eacute;c&eacute;dents
                                ou des alertes &agrave; la fraude de prestataires de service comme les services de v&eacute;rification
                                de l&rsquo;identit&eacute; dans le cadre de nos actions de pr&eacute;vention des fraudes
                                et d&rsquo;&eacute;valuation des risques. Nous pouvons recevoir des informations vous concernant
                                et concernant vos activit&eacute;s sur et en dehors de la Plateforme My Ice Tool au travers
                                de partenariats, ou concernant vos exp&eacute;riences et interactions de la part de nos r&eacute;seaux
                                partenaires de publicit&eacute;.</span>
                        </li>
                    </ul>
                    <h4 style="line-height: 1.32; margin-top: 19pt; margin-bottom: 11pt; background-color: #ffffff;"><strong><span style="font-size: 13.5pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">2. UTILISATION DES INFORMATIONS QUE NOUS COLLECTONS</span></strong></h4>
                    <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 11pt; background-color: #ffffff;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Nous utilisons, stockons et traitons les informations vous concernant afin d&rsquo;alimenter, comprendre, am&eacute;liorer et d&eacute;velopper la Plateforme My Ice Tool, et pour cr&eacute;er et maintenir un environnement de confiance mieux s&eacute;curis&eacute;.</span></p>
                    <h5 style="line-height: 1.32; margin-top: 19pt; margin-bottom: 11pt; background-color: #ffffff;"><strong><span style="font-size: 12pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">2.1 Alimenter, am&eacute;liorer et d&eacute;velopper la Plateforme My Ice Tool.</span></strong></h5>
                    <ul style="margin-top: 0pt; margin-bottom: 0pt;">
                        <li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Vous permettre d&rsquo;acc&eacute;der &agrave; et d&rsquo;utiliser la Plateforme My Ice Tool.</span></li>
                        <li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Vous permettre de communiquer avec d&rsquo;autres Membres.</span></li>
                        <li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Assurer le fonctionnement, prot&eacute;ger, am&eacute;liorer et optimiser la Plateforme et l&rsquo;exp&eacute;rience My Ice Tool, en r&eacute;alisant des analyses et des &eacute;tudes par exemple.</span></li>
                        <li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Personnaliser ou adapter autrement votre exp&eacute;rience en proc&eacute;dant, entre autres, au tri des r&eacute;sultats de recherche ou en affichant des pubs en fonction de vos recherches, de l&rsquo;historique de vos r&eacute;servations et de vos pr&eacute;f&eacute;rences.</span></li>
                        <li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Fournir une assistance utilisateurs.</span></li>
                        <li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Vous adresser des messages d&rsquo;assistance ou relatifs aux services , comme tels que des mises &agrave; jour, des alertes de s&eacute;curit&eacute; et des notifications de compte.</span></li>
                    </ul>
                    <h5 style="line-height: 1.32; margin-top: 19pt; margin-bottom: 11pt; background-color: #ffffff;"><strong><span style="font-size: 12pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">2.2 Cr&eacute;er et maintenir un environnement de confiance mieux s&eacute;curis&eacute;.</span></strong></h5>
                    <ul style="margin-top: 0pt; margin-bottom: 0pt;">
                        <li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">D&eacute;tecter et pr&eacute;venir les fraudes, spams, abus, incidents de s&eacute;curit&eacute; et autres activit&eacute;s pr&eacute;judiciables.</span></li>
                        <li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Mener des enqu&ecirc;tes et des &eacute;valuations de risque.</span></li>
                        <li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">V&eacute;rifier ou authentifier les informations ou identifications transmises par vos soins (comme par exemple v&eacute;rifier l&rsquo;adresse de votre Logement ou comparer la photo d&rsquo;identification avec une autre photo transmise par vous).</span></li>
                        <li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Proc&eacute;der &agrave; des v&eacute;rifications avec des bases de donn&eacute;es ou d'autres sources d&rsquo;information.</span></li>
                        <li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Respecter nos obligations l&eacute;gales.</span></li>
                        <li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">R&eacute;soudre tous litiges que nous pourrions avoir avec nos utilisateurs et faire valoir nos contrats avec les tiers.</span></li>
                        <li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Faire appliquer nos </span>
                            <a
                                style="text-decoration: none;" href="https://www.airbnb.fr/terms"><span style="font-size: 10.5pt; font-family: Arial; color: #008489; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: underline; -webkit-text-decoration-skip: none; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">Conditions de service</span></a>
                                <span
                                    style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">, </span><a style="text-decoration: none;" href="https://www.airbnb.fr/terms/payments_terms"><span style="font-size: 10.5pt; font-family: Arial; color: #008489; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: underline; -webkit-text-decoration-skip: none; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">Conditions de paiement</span></a>
                                    <span
                                        style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">, ainsi que nos autres politiques.</span>
                        </li>
                    </ul>
                    <h4 style="line-height: 1.32; margin-top: 19pt; margin-bottom: 11pt; background-color: #ffffff;"><strong><span style="font-size: 13.5pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">3. PARTAGE ET DIVULGATION</span></strong></h4>
                    <h5 style="line-height: 1.32; margin-top: 19pt; margin-bottom: 11pt; background-color: #ffffff;"><strong><span style="font-size: 12pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">3.1 Profils, Annonces et autres Informations Publiques.</span></strong></h5>
                    <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 11pt; background-color: #ffffff;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">La Plateforme My Ice Tool vous permet de publier des informations accessibles au public. Par exemple,</span></p>
                    <ul style="margin-top: 0pt; margin-bottom: 0pt;">
                        <li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Des parties de votre page de profil public, comme votre pr&eacute;nom, votre description, et votre ville sont publiquement accessibles.</span></li>
                        <li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Les pages d&rsquo;Annonces publiques peuvent &ecirc;tre vues par le public et comprennent des informations comme l&rsquo;emplacement approximatif du Logement ou de l&rsquo;Exp&eacute;rience (quartier et ville), la description de l&rsquo;Annonce, le calendrier de disponibilit&eacute;, la photo du profil public de l&rsquo;H&ocirc;te, les informations agr&eacute;g&eacute;es sur la demande (tel que le nombre de consultations de la page sur une p&eacute;riode donn&eacute;e), ainsi que toutes informations compl&eacute;mentaires que l&rsquo;H&ocirc;te choisit de partager.</span></li>
                        <li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Une fois la r&eacute;servation achev&eacute;e, les Voyageurs et les H&ocirc;tes peuvent &eacute;crire des commentaires et s&rsquo;&eacute;valuer mutuellement. Les commentaires font partie de votre page de profil public.</span></li>
                        <li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Si vous communiquez un contenu dans un forum de discussion ou postez un contenu sur un r&eacute;seau social, ou utilisez une fonctionnalit&eacute; similaire sur la Plateforme My Ice Tool, ce contenu est rendu public.</span></li>
                    </ul>
                    <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 11pt; background-color: #ffffff;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Les informations que vous partagez publiquement sur la Plateforme My Ice Tool peuvent &ecirc;tre index&eacute;es via des moteurs de recherche de tiers. Dans certains cas, il vous est possible de d&eacute;sactiver cette fonctionnalit&eacute; dans vos param&egrave;tres (dans la rubrique &laquo; Compte &raquo;). Si vous modifiez vos param&egrave;tres ou votre contenu accessible au public, il est possible que ces moteurs de recherche ne puissent pas mettre &agrave; jour leurs bases de donn&eacute;es. Nous n&rsquo;avons aucun contr&ocirc;le sur les pratiques des moteurs de recherche tiers, lesquels peuvent utiliser des m&eacute;moires cache contenant des informations qui ne sont plus &agrave; jour sur vous.</span></p>
                    <h5 style="line-height: 1.32; margin-top: 19pt; margin-bottom: 11pt; background-color: #ffffff;"><strong><span style="font-size: 12pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">3.2 Prestataires de service.</span></strong></h5>
                    <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 11pt; background-color: #ffffff;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Nous recourons &agrave; divers prestataires de service tiers afin de nous aider &agrave; fournir les services en lien avec la Plateforme My Ice Tool. Les prestataires de service peuvent se trouver au sein de l&rsquo;Espace &eacute;conomique europ&eacute;en (&laquo; </span><strong><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">EEE</span></strong>
                        <span
                            style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">
                        &raquo;) ou en dehors. &Agrave; titre d&rsquo;exemple, les prestataires de service peuvent nous aider
                            &agrave; : (i) v&eacute;rifier ou authentifier votre identit&eacute;, (ii) v&eacute;rifier les
                            informations par rapport &agrave; des bases de donn&eacute;es publiques, (iii) effectuer des
                            v&eacute;rifications d&rsquo;ant&eacute;c&eacute;dents, mettre en &oelig;uvre la pr&eacute;vention
                            des fraudes et l&rsquo;&eacute;valuation des risques, ou (iv) fournir l&rsquo;assistance utilisateurs,
                            la publicit&eacute; ou les services de paiement. Ces prestataires de service disposent d&rsquo;un
                            acc&egrave;s limit&eacute; &agrave; vos informations dans le cadre de l&rsquo;ex&eacute;cution
                            de ces t&acirc;ches pour notre compte, et ont une obligation contractuelle de les utiliser en
                            conformit&eacute; avec les termes de la pr&eacute;sente Charte de protection des donn&eacute;es
                            &agrave; caract&egrave;re personnel.</span>
                    </p>
                    <h5 style="line-height: 1.32; margin-top: 19pt; margin-bottom: 11pt; background-color: #ffffff;"><strong><span style="font-size: 12pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">3.3 Services additionnels fournis par les H&ocirc;tes.</span></strong></h5>
                    <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 11pt; background-color: #ffffff;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Les H&ocirc;tes peuvent utiliser des services tiers disponibles par le biais de la Plateforme My Ice Tool pour les aider dans la gestion de leur Logement ou la prestation de services suppl&eacute;mentaires, tels que des services de m&eacute;nage ou des fournisseurs de cadenas. Les H&ocirc;tes peuvent utiliser les fonctionnalit&eacute;s de la Plateforme My Ice Tool pour partager des informations concernant le Voyageur (notamment les dates d&rsquo;arriv&eacute;e et de d&eacute;part, le nom du Voyageur, son num&eacute;ro de t&eacute;l&eacute;phone et adresse e-mail anonyme) avec le prestataire de service tiers aux fins de coordonner le s&eacute;jour, de g&eacute;rer le Logement ou de fournir d&rsquo;autres services.</span></p>
                    <h5 style="line-height: 1.32; margin-top: 19pt; margin-bottom: 11pt; background-color: #ffffff;"><strong><span style="font-size: 12pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">3.4 My Ice Tool Payments.</span></strong></h5>
                    <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 11pt; background-color: #ffffff;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">My Ice Tool Payments peut partager vos informations &agrave; caract&egrave;re personnel afin de : (i) fournir les Services de paiement, (ii) faciliter votre utilisation de la Plateforme My Ice Tool, et (iii) commercialiser conjointement des produits ou services en votre faveur avec d&rsquo;autres soci&eacute;t&eacute;s financi&egrave;res tierces avec lesquelles My Ice Tool Payments a conclu un contrat formel. Vous pouvez vous d&eacute;sabonner ou refuser de recevoir ces communications dans vos param&egrave;tres (dans la rubrique &laquo; Compte &raquo;).</span></p>
                    <h5 style="line-height: 1.32; margin-top: 19pt; margin-bottom: 11pt; background-color: #ffffff;"><strong><span style="font-size: 12pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">3.5 S&eacute;curit&eacute; et conformit&eacute; avec la loi.</span></strong></h5>
                    <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 11pt; background-color: #ffffff;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">My Ice Tool peut divulguer vos informations aux tribunaux, autorit&eacute;s gouvernementales ou charg&eacute;es de l&rsquo;application de la loi ou &agrave; des tiers autoris&eacute;s, si la loi l&rsquo;exige ou si une telle divulgation est raisonnablement jug&eacute;e n&eacute;cessaire : (i) afin de se conformer au processus judiciaire et de donner suite aux r&eacute;clamations pr&eacute;sent&eacute;es contre My Ice Tool, (ii) pour r&eacute;pondre &agrave; des demandes v&eacute;rifi&eacute;es dans le cadre d&rsquo;une enqu&ecirc;te judiciaire ou d&rsquo;une activit&eacute; ill&eacute;gale pr&eacute;tendue ou soup&ccedil;onn&eacute;e ou de toute autre activit&eacute; qui peut nous exposer, vous exposer ou exposer nos utilisateurs &agrave; une responsabilit&eacute; l&eacute;gale, (iii) aux fins d&rsquo;ex&eacute;cuter et d&rsquo;administrer nos </span>
                        <a
                            style="text-decoration: none;" href="https://www.airbnb.fr/terms"><span style="font-size: 10.5pt; font-family: Arial; color: #008489; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: underline; -webkit-text-decoration-skip: none; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">Conditions de service</span></a>
                            <span
                                style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">
                            ou d&rsquo;autres accords pass&eacute;s avec les Membres, (iv) dans le cadre d&rsquo;enqu&ecirc;te
                                antifraude, de l&rsquo;&eacute;valuation des risques, de l&rsquo;assistance aux utilisateurs,
                                du d&eacute;veloppement de produit et &agrave; des fins de d&eacute;bogage, ou (v) pour prot&eacute;ger
                                les droits, les biens ou la s&eacute;curit&eacute; personnelle de My Ice Tool, ses employ&eacute;s,
                                ses Membres ou du public.</span>
                    </p>
                    <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 11pt; background-color: #ffffff;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Nous t&acirc;cherons d&rsquo;informer les Membres de ces demandes, except&eacute; dans les cas suivants : (i) lorsque toute notification est interdite par la proc&eacute;dure judiciaire elle-m&ecirc;me, par ordonnance du tribunal rendue &agrave; notre effet, ou conform&eacute;ment &agrave; la loi en vigueur, ou (ii) si nous estimons que le fait de vous informer serait sans int&eacute;r&ecirc;t, inefficace, pourrait constituer un risque de blessure ou de pr&eacute;judice corporel &agrave; un individu ou un groupe, ou cr&eacute;er ou intensifier un risque de fraude concernant les biens de My Ice Tool, ses Membres et la Plateforme (collectivement, &laquo; </span><strong><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Sc&eacute;narios &agrave; Risque</span></strong>
                        <span
                            style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">
                        &raquo;). Dans les cas o&ugrave; nous nous conformons aux exigences l&eacute;gales sans pr&eacute;avis
                            pour les raisons susmentionn&eacute;es, nous essaierons d&rsquo;informer a posteriori le Membre
                            concern&eacute; de la demande si nous estimons en toute bonne foi que nous ne sommes plus l&eacute;galement
                            tenus de ne pas le faire et qu&rsquo;aucun Sc&eacute;nario &agrave; Risque ne s&rsquo;applique.</span>
                    </p>
                    <h5 style="line-height: 1.32; margin-top: 19pt; margin-bottom: 11pt; background-color: #ffffff;"><strong><span style="font-size: 12pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">3.7 Widgets.</span></strong></h5>
                    <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 11pt; background-color: #ffffff;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Nous pouvons diffuser des sections de la Plateforme My Ice Tool (par ex. votre page d&rsquo;Annonce) sur des sites op&eacute;r&eacute;s par les partenaires de My Ice Tool, &agrave; l&rsquo;aide de technologies comme les widgets ou des API. Si vos Annonces sont diffus&eacute;es sur le site d&rsquo;un partenaire, les informations de votre page de profil public pourront &eacute;galement &ecirc;tre affich&eacute;es.</span></p>
                    <h5 style="line-height: 1.32; margin-top: 19pt; margin-bottom: 11pt; background-color: #ffffff;"><strong><span style="font-size: 12pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">3.8 Autorit&eacute;s fiscales.</span></strong></h5>
                    <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 11pt; background-color: #ffffff;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Dans les juridictions o&ugrave; nous nous chargeons de la Collecte et de l&rsquo;acquittement de la Taxe de s&eacute;jour telle que d&eacute;crite dans la section &laquo; Fiscalit&eacute; &raquo; des </span>
                        <a
                            style="text-decoration: none;" href="https://www.airbnb.fr/terms"><span style="font-size: 10.5pt; font-family: Arial; color: #008489; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: underline; -webkit-text-decoration-skip: none; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">Conditions de service</span></a>
                            <span
                                style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">, les H&ocirc;tes et Voyageurs nous autorisent de mani&egrave;re expresse, et sans pr&eacute;avis
                                ult&eacute;rieur, &agrave; divulguer les donn&eacute;es et autres informations relatives
                                aux H&ocirc;tes et Voyageurs et &agrave; leurs transactions, r&eacute;servations, Logements
                                et Taxe de s&eacute;jour aux autorit&eacute;s fiscales concern&eacute;es, y compris mais
                                sans s&rsquo;y limiter le nom de l&rsquo;H&ocirc;te ou du Voyageur, les adresses correspondant
                                &agrave; l&rsquo;annonce, les dates et les montants de la transaction, le(s) num&eacute;ro(s)
                                d&rsquo;identification fiscale, le montant des taxes collect&eacute;es (ou dues) par les
                                H&ocirc;tes aupr&egrave;s des Voyageurs, et les coordonn&eacute;es.</span>
                    </p>
                    <h5 style="line-height: 1.32; margin-top: 19pt; margin-bottom: 11pt; background-color: #ffffff;"><strong><span style="font-size: 12pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">3.9 Renseignements sur l&rsquo;H&ocirc;te fournis aux Clients des programmes de voyages d&rsquo;affaires.</span></strong></h5>
                    <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 11pt; background-color: #ffffff;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Si une r&eacute;servation indique qu&rsquo;elle est effectu&eacute;e &agrave; titre professionnel, et par un Voyageur qui est rattach&eacute; &agrave; une soci&eacute;t&eacute; ou autre organisation appartenant &agrave; notre Programme de voyages d&rsquo;affaires (individuellement ou conjointement, une &laquo; </span><strong><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Entreprise</span></strong>
                        <span
                            style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">
                        &raquo;), nous pouvons divulguer les informations de r&eacute;servation &agrave; l&rsquo;Entreprise,
                            comme le nom de l&rsquo;H&ocirc;te, l&rsquo;adresse du Logement, la tarification, les d&eacute;tails
                            de l&rsquo;Annonce et autres informations connexes. Sur demande de l&rsquo;Entreprise, nous pouvons
                            &eacute;galement communiquer ces informations &agrave; des tiers charg&eacute;s par elle de l&rsquo;organisation
                            du voyage, des rapports financiers, de l&rsquo;administration du personnel, de la gestion de
                            crise ou autres services.</span>
                    </p>
                    <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 11pt; background-color: #ffffff;">&nbsp;</p>
                    <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 11pt; background-color: #ffffff;">&nbsp;</p>
                    <h5 style="line-height: 1.32; margin-top: 19pt; margin-bottom: 11pt; background-color: #ffffff;"><strong><span style="font-size: 12pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">3.10 Cessions d&rsquo;entreprise.</span></strong></h5>
                    <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 11pt; background-color: #ffffff;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Si My Ice Tool entreprend ou est impliqu&eacute;e dans une fusion, acquisition, restructuration, cession d&rsquo;actifs ou proc&eacute;dure de faillite ou d&rsquo;insolvabilit&eacute;, elle pourra vendre, c&eacute;der ou partager tout ou partie de ses actifs, y compris vos informations. Dans ce cas, nous vous informerons avant que vos donn&eacute;es &agrave; caract&egrave;re personnel ne soient transf&eacute;r&eacute;es et ne soient r&eacute;gies par une autre charte de protection des donn&eacute;es &agrave; caract&egrave;re personnel.</span></p>
                    <h5 style="line-height: 1.32; margin-top: 19pt; margin-bottom: 11pt; background-color: #ffffff;"><strong><span style="font-size: 12pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">3.11 Donn&eacute;es agr&eacute;g&eacute;es.</span></strong></h5>
                    <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 11pt; background-color: #ffffff;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Nous pouvons &eacute;galement partager des informations agr&eacute;g&eacute;es (informations concernant nos utilisateurs que nous combinons de fa&ccedil;on &agrave; ce qu&rsquo;elles ne puissent plus identifier ou r&eacute;f&eacute;rencer un utilisateur individuel) et des renseignements ne permettant pas d&rsquo;identifier une personne &agrave; des fins d&rsquo;analyse du secteur et du march&eacute;, de profilage d&eacute;mographique, pour des raisons commerciales et publicitaires et autres finalit&eacute;s professionnelles.</span></p>
                    <h5 style="line-height: 1.32; margin-top: 19pt; margin-bottom: 11pt; background-color: #ffffff;"><strong><span style="font-size: 12pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">4.2 Lien vers des Comptes de tiers.</span></strong></h5>
                    <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 11pt; background-color: #ffffff;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Vous pouvez lier votre Compte My Ice Tool &agrave; votre compte ouvert sur un r&eacute;seau social tiers. Vos contacts figurant sur ces services de tiers sont r&eacute;f&eacute;renc&eacute;s comme &laquo; Amis &raquo;. Lorsque vous cr&eacute;ez ce lien :</span></p>
                    <ul style="margin-top: 0pt; margin-bottom: 0pt;">
                        <li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">certaines des informations que vous nous fournissez &agrave; partir des liens entre vos comptes peuvent &ecirc;tre publi&eacute;es sur le profil de votre Compte My Ice Tool ;</span></li>
                        <li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">vos activit&eacute;s sur la Plateforme My Ice Tool peuvent &ecirc;tre montr&eacute;es &agrave; vos Amis sur la Plateforme et/ou ce site tiers ;</span></li>
                        <li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">un lien vers votre profil public figurant sur ce site tiers de r&eacute;seau social peut &ecirc;tre inclus dans votre profil public My Ice Tool ;</span></li>
                        <li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">les autres utilisateurs My Ice Tool peuvent voir tous les Amis communs que vous pourriez avoir avec eux ou, le cas &eacute;ch&eacute;ant, que vous &ecirc;tes un Ami de leur Ami, ;</span></li>
                        <li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">les autres utilisateurs My Ice Tool peuvent voir les &eacute;coles, villes d&rsquo;origine ou autres groupes que vous avez en commun avec eux tels qu&rsquo;ils sont &eacute;num&eacute;r&eacute;s sur vos r&eacute;seaux sociaux li&eacute;s ;</span></li>
                        <li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">les informations que vous nous divulguez en liant vos comptes peuvent &ecirc;tre conserv&eacute;es, trait&eacute;es et transmises &agrave; des fins de pr&eacute;vention des fraudes et d&rsquo;&eacute;valuation des risques, et</span></li>
                        <li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">la publication et l&rsquo;affichage des informations que vous fournissez &agrave; My Ice Tool par le biais de ces liens d&eacute;pendent des param&egrave;tres et autorisations que vous aurez d&eacute;finis sur la Plateforme My Ice Tool et le site tiers.</span></li>
                    </ul>
                    <h5 style="line-height: 1.32; margin-top: 19pt; margin-bottom: 11pt; background-color: #ffffff;"><strong><span style="font-size: 12pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">4.3 Google Maps/Earth.</span></strong></h5>
                    <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 11pt; background-color: #ffffff;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Certaines parties de la plateforme My Ice Tool utilisent les services de cartographie Google Maps/Google Earth, y compris les API Google Maps. L&rsquo;utilisation de Google Maps/Earth est soumise aux </span>
                        <a
                            style="text-decoration: none;" href="http://www.google.com/intl/en_us/help/terms_maps.html"><span style="font-size: 10.5pt; font-family: Arial; color: #008489; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: underline; -webkit-text-decoration-skip: none; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">Conditions d&rsquo;utilisation compl&eacute;mentaires de Google Maps/Earth</span></a>
                            <span
                                style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">
                            et &agrave; la </span><a style="text-decoration: none;" href="http://www.google.com/privacy.html"><span style="font-size: 10.5pt; font-family: Arial; color: #008489; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: underline; -webkit-text-decoration-skip: none; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">Politique de confidentialit&eacute; de Google</span></a>
                                <span
                                    style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">.</span>
                    </p>
                    <h4 style="line-height: 1.32; margin-top: 19pt; margin-bottom: 11pt; background-color: #ffffff;"><strong><span style="font-size: 13.5pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">5. PARTENAIRES TIERS ET INT&Eacute;GRATIONS</span></strong></h4>
                    <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 11pt; background-color: #ffffff;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">La Plateforme My Ice Tool peut contenir des liens vers des services ou sites Web tiers, tels que les int&eacute;grations de tiers, les services en partage de marques, ou les services de marque tierce (&laquo; </span><strong><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Partenaires tiers</span></strong>
                        <span
                            style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">
                        &raquo;). My Ice Tool ne d&eacute;tient pas ni ne contr&ocirc;le ces Partenaires tiers et lors de
                            vos interactions avec ces derniers, vous pouvez soit fournir des informations directement au
                            Partenaire tiers, soit &agrave; My Ice Tool ou aux deux. Ces Partenaires tiers auront leurs propres
                            r&egrave;gles en mati&egrave;re de collecte, d&rsquo;utilisation et de divulgation des informations.
                            Nous vous encourageons &agrave; lire les politiques de confidentialit&eacute; des autres sites
                            Web que vous consultez.</span>
                    </p>
                    <h4 style="line-height: 1.32; margin-top: 19pt; margin-bottom: 11pt; background-color: #ffffff;"><strong><span style="font-size: 13.5pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">6. VOS CHOIX</span></strong></h4>
                    <h5 style="line-height: 1.32; margin-top: 19pt; margin-bottom: 11pt; background-color: #ffffff;"><strong><span style="font-size: 12pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">6.1 Acc&egrave;s et mise &agrave; jour.</span></strong></h5>
                    <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 11pt; background-color: #ffffff;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Vous pouvez revoir, mettre &agrave; jour ou supprimer les informations figurant dans votre Compte My Ice Tool en vous connectant &agrave; votre Compte My Ice Tool et en configurant les param&egrave;tres de votre Compte et votre profil.</span></p>
                    <h5 style="line-height: 1.32; margin-top: 19pt; margin-bottom: 11pt; background-color: #ffffff;"><strong><span style="font-size: 12pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">6.2 Suppression de compte.</span></strong></h5>
                    <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 11pt; background-color: #ffffff;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Pour obtenir des informations sur la mani&egrave;re de supprimer votre Compte My Ice Tool, veuillez vous rendre &agrave; l&rsquo;adresse </span>
                        <a
                            style="text-decoration: none;" href="https://www.airbnb.fr/help"><span style="font-size: 10.5pt; font-family: Arial; color: #008489; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: underline; -webkit-text-decoration-skip: none; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">www.My Ice Tool.com/help</span></a>
                            <span
                                style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">. Veuillez noter que les informations que vous avez partag&eacute;es avec d&rsquo;autres utilisateurs
                                (comme les Commentaires ou les publications sur les forums) peuvent continuer d&rsquo;&ecirc;tre
                                visibles du public sur la Plateforme My Ice Tool en lien avec votre pr&eacute;nom, m&ecirc;me
                                apr&egrave;s la suppression de votre Compte My Ice Tool.</span>
                    </p>
                    <h4 style="line-height: 1.32; margin-top: 19pt; margin-bottom: 11pt; background-color: #ffffff;"><strong><span style="font-size: 13.5pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">8. S&Eacute;CURIT&Eacute;</span></strong></h4>
                    <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 11pt; background-color: #ffffff;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Nous mettons en place et actualisons en permanence des mesures administratives, techniques et physiques en mati&egrave;re de s&eacute;curit&eacute; pour prot&eacute;ger vos informations contre les acc&egrave;s, pertes, destructions ou alt&eacute;rations non autoris&eacute;s. Toutefois, Internet n&rsquo;est pas un environnement s&eacute;curis&eacute; &agrave; 100 % et nous ne pouvons donc pas garantir la s&eacute;curit&eacute; de la transmission ou du stockage de vos informations.</span></p>
                    <h4 style="line-height: 1.32; margin-top: 19pt; margin-bottom: 11pt; background-color: #ffffff;"><strong><span style="font-size: 13.5pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">9. MODIFICATIONS DE LA PR&Eacute;SENTE CHARTE DE PROTECTION DES DONN&Eacute;ES &Agrave; CARACT&Egrave;RE PERSONNEL</span></strong></h4>
                    <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 11pt; background-color: #ffffff;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">My Ice Tool se r&eacute;serve le droit d&rsquo;apporter toute modification &agrave; la pr&eacute;sente Charte de protection des donn&eacute;es &agrave; caract&egrave;re personnel &agrave; tout moment, conform&eacute;ment &agrave; la pr&eacute;sente clause. Si nous apportons une modification &agrave; la pr&eacute;sente Charte de protection des donn&eacute;es &agrave; caract&egrave;re personnel, nous publierons la nouvelle version sur la Plateforme My Ice Tool et actualiserons la date de &laquo; Derni&egrave;re mise &agrave; jour &raquo; figurant en haut de la pr&eacute;sente Charte de protection des donn&eacute;es &agrave; caract&egrave;re personnel. Nous vous informerons &eacute;galement de la modification par e-mail dans un d&eacute;lai minimum de trente (30) jours avant la date de sa prise d&rsquo;effet. Si vous n&rsquo;&ecirc;tes pas d&rsquo;accord avec les termes de la nouvelle Charte de protection des donn&eacute;es &agrave; caract&egrave;re personnel, vous pouvez supprimer votre Compte. Si vous ne supprimez pas votre Compte avant la date d&rsquo;entr&eacute;e en vigueur de la nouvelle Charte de protection des donn&eacute;es &agrave; caract&egrave;re personnel, la poursuite de l&rsquo;acc&egrave;s et de l&rsquo;utilisation de la Plateforme My Ice Tool vaudront acceptation de la Charte de protection des donn&eacute;es &agrave; caract&egrave;re personnel r&eacute;vis&eacute;e.</span></p>
                    <h4 style="line-height: 1.32; margin-top: 19pt; margin-bottom: 11pt; background-color: #ffffff;"><strong><span style="font-size: 13.5pt; font-family: Arial; color: #484848; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">10. CONTACT</span></strong></h4>
                    <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 11pt; background-color: #ffffff;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Si vous avez des questions ou des plaintes &agrave; formuler concernant la pr&eacute;sente Charte de protection des donn&eacute;es &agrave; caract&egrave;re personnel ou les pratiques de My Ice Tool en mati&egrave;re de traitement : </span></p>
                    <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 11pt; background-color: #ffffff;"><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Vous pouvez nous envoyer un </span>
                        <span
                            style="font-size: 10.5pt; font-family: Arial; color: #008489; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">e-mail</span><span style="font-size: 10.5pt; font-family: Arial; color: #484848; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> .</span></p>
                    <p>&nbsp;</p>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection